import type { Property, Agent } from '@/types'

// ─── Agents ───────────────────────────────────────────────────────────────────

export const mockAgents: Agent[] = [
  {
    id: 'agent-001',
    name: 'Sophie Marchand',
    slug: 'sophie-marchand',
    photo: 'https://res.cloudinary.com/demo/image/upload/sample.jpg',
    phone: '+33 6 12 34 56 78',
    email: 'sophie.marchand@sweetestate.eu',
    title: {
      en: 'Senior Property Consultant',
      fr: 'Consultante Immobilière Senior',
      es: 'Consultora Inmobiliaria Senior',
      ca: 'Consultora Immobiliària Senior',
    },
    bio: {
      en: 'Sophie has over 12 years of experience in French and Spanish luxury real estate. Fluent in four languages, she specialises in high-end residential and coastal properties from Barcelona to the Côte d\'Azur.',
      fr: 'Sophie possède plus de 12 ans d\'expérience dans l\'immobilier de luxe français et espagnol. Maîtrisant quatre langues, elle est spécialisée dans les propriétés résidentielles haut de gamme et les biens côtiers de Barcelone à la Côte d\'Azur.',
      es: 'Sophie cuenta con más de 12 años de experiencia en el sector inmobiliario de lujo francés y español. Con dominio de cuatro idiomas, se especializa en propiedades residenciales de alta gama y propiedades costeras desde Barcelona hasta la Costa Azul.',
      ca: 'La Sophie té més de 12 anys d\'experiència en el sector immobiliari de luxe francès i espanyol. Amb domini de quatre idiomes, s\'especialitza en propietats residencials d\'alta gamma i propietats costaneres des de Barcelona fins a la Costa Blava.',
    },
    listings: [],
  },
  {
    id: 'agent-002',
    name: 'Carlos Rivera',
    slug: 'carlos-rivera',
    photo: 'https://res.cloudinary.com/demo/image/upload/sample.jpg',
    phone: '+34 6 98 76 54 32',
    email: 'carlos.rivera@sweetestate.eu',
    title: {
      en: 'Commercial & Investment Specialist',
      fr: 'Spécialiste Commercial & Investissement',
      es: 'Especialista en Comercial e Inversión',
      ca: 'Especialista en Comercial i Inversió',
    },
    bio: {
      en: 'Carlos brings 15 years of expertise in commercial real estate and investment portfolios across Spain and Portugal. He advises institutional clients, family offices, and individual investors on high-yield opportunities.',
      fr: 'Carlos apporte 15 ans d\'expertise en immobilier commercial et en portefeuilles d\'investissement en Espagne et au Portugal. Il conseille des clients institutionnels, des family offices et des investisseurs individuels sur des opportunités à haut rendement.',
      es: 'Carlos aporta 15 años de experiencia en el sector inmobiliario comercial y carteras de inversión en España y Portugal. Asesora a clientes institucionales, family offices e inversores individuales en oportunidades de alta rentabilidad.',
      ca: 'En Carlos aporta 15 anys d\'experiència en el sector immobiliari comercial i carteres d\'inversió a Espanya i Portugal. Assessora clients institucionals, family offices i inversors individuals en oportunitats d\'alta rendibilitat.',
    },
    listings: [],
  },
  {
    id: 'agent-003',
    name: 'Isabelle Dupont',
    slug: 'isabelle-dupont',
    photo: 'https://res.cloudinary.com/demo/image/upload/sample.jpg',
    phone: '+33 6 55 44 33 22',
    email: 'isabelle.dupont@sweetestate.eu',
    title: {
      en: 'Rental & Relocation Advisor',
      fr: 'Conseillère en Location & Relocalisation',
      es: 'Asesora de Alquiler y Reubicación',
      ca: 'Assessora de Lloguer i Trasllat',
    },
    bio: {
      en: 'Isabelle specialises in long-term and short-term rentals across Paris, Lyon, and the French Riviera. With a background in international relocation, she guides expat families and corporate clients through every step of the rental process.',
      fr: 'Isabelle est spécialisée dans les locations longue et courte durée à Paris, Lyon et la Riviera française. Forte d\'une expérience en relocalisation internationale, elle accompagne les familles expatriées et les clients entreprises à chaque étape du processus locatif.',
      es: 'Isabelle se especializa en alquileres a largo y corto plazo en París, Lyon y la Riviera francesa. Con experiencia en reubicación internacional, guía a familias expatriadas y clientes corporativos en cada paso del proceso de alquiler.',
      ca: 'La Isabelle s\'especialitza en lloguers a llarg i curt termini a París, Lió i la Riviera francesa. Amb experiència en trasllats internacionals, guia famílies expatriades i clients corporatius en cada pas del procés de lloguer.',
    },
    listings: [],
  },
]

// ─── Properties ───────────────────────────────────────────────────────────────

const IMG = 'https://res.cloudinary.com/demo/image/upload/sample.jpg'

export const mockProperties: Property[] = [
  // ── 1. Residential Sale — Barcelona ─────────────────────────────────────────
  {
    id: 'prop-001',
    slug: 'modernist-apartment-barcelona-eixample',
    title: {
      en: 'Modernist Apartment in the Eixample',
      fr: 'Appartement Moderniste dans l\'Eixample',
      es: 'Piso Modernista en el Eixample',
      ca: 'Pis Modernista a l\'Eixample',
    },
    description: {
      en: 'A stunning four-bedroom apartment occupying the principal floor of a Catalan Modernista building, steps from Passeig de Gràcia. Original mosaic floors, ornate ceilings, and a south-facing balcony are complemented by a fully renovated kitchen and bathrooms.',
      fr: 'Un magnifique appartement de quatre chambres occupant l\'étage principal d\'un immeuble du Modernisme catalan, à deux pas du Passeig de Gràcia. Sols en mosaïque d\'origine, plafonds ornementés et balcon exposé sud se marient à une cuisine et des salles de bains entièrement rénovées.',
      es: 'Un espectacular piso de cuatro habitaciones que ocupa el piso principal de un edificio del Modernismo catalán, a pasos del Passeig de Gràcia. Suelos de mosaico originales, techos ornamentados y un balcón orientado al sur se complementan con una cocina y baños totalmente renovados.',
      ca: 'Un espectacular pis de quatre habitacions que ocupa el pis principal d\'un edifici del Modernisme català, a pocs passos del Passeig de Gràcia. Terres de mosaic originals, sostres ornamentats i un balcó orientat al sud es complementen amb una cuina i banys totalment renovats.',
    },
    type: 'residential_sale',
    status: 'available',
    price: 1250000,
    priceLabel: '€1,250,000',
    bedrooms: 4,
    bathrooms: 3,
    receptionRooms: 2,
    squareMeters: 210,
    address: 'Carrer de Provença 312, 1r 1a',
    city: 'Barcelona',
    postcode: '08008',
    country: 'Spain',
    coordinates: { lat: 41.3968, lng: 2.1616 },
    features: [
      { en: 'Original Modernista mosaic floors', fr: 'Sols en mosaïque moderniste d\'origine', es: 'Suelos de mosaico modernista originales', ca: 'Terres de mosaic modernista originals' },
      { en: 'South-facing balcony', fr: 'Balcon exposé sud', es: 'Balcón orientado al sur', ca: 'Balcó orientat al sud' },
      { en: 'Fully renovated kitchen', fr: 'Cuisine entièrement rénovée', es: 'Cocina totalmente renovada', ca: 'Cuina totalment renovada' },
      { en: 'Private parking space', fr: 'Place de parking privée', es: 'Plaza de aparcamiento privada', ca: 'Plaça d\'aparcament privada' },
      { en: 'Air conditioning', fr: 'Climatisation', es: 'Aire acondicionado', ca: 'Aire condicionat' },
    ],
    images: [IMG, IMG, IMG],
    agent: {
      id: 'agent-001',
      name: 'Sophie Marchand',
      slug: 'sophie-marchand',
      photo: IMG,
      title: { en: 'Senior Property Consultant', fr: 'Consultante Immobilière Senior', es: 'Consultora Inmobiliaria Senior', ca: 'Consultora Immobiliària Senior' },
      phone: '+33 6 12 34 56 78',
      email: 'sophie.marchand@sweetestate.eu',
    },
    listedAt: '2025-11-15',
  },

  // ── 2. Luxury — Côte d'Azur ──────────────────────────────────────────────────
  {
    id: 'prop-002',
    slug: 'villa-panoramique-cap-antibes',
    title: {
      en: 'Panoramic Villa on Cap d\'Antibes',
      fr: 'Villa Panoramique au Cap d\'Antibes',
      es: 'Villa Panorámica en Cap d\'Antibes',
      ca: 'Vil·la Panoràmica al Cap d\'Antibes',
    },
    description: {
      en: 'An exceptional Belle Époque villa perched on Cap d\'Antibes with sweeping sea views from every room. The 500 m² residence features six en-suite bedrooms, an infinity pool, a wine cellar, and a landscaped garden of over 3,000 m².',
      fr: 'Une villa Belle Époque d\'exception perchée sur le Cap d\'Antibes avec des vues sur la mer depuis chaque pièce. La résidence de 500 m² comprend six chambres en suite, une piscine à débordement, une cave à vin et un jardin paysager de plus de 3 000 m².',
      es: 'Una excepcional villa Belle Époque encaramada en el Cap d\'Antibes con amplias vistas al mar desde cada habitación. La residencia de 500 m² cuenta con seis habitaciones en suite, piscina infinita, bodega y jardín paisajístico de más de 3.000 m².',
      ca: 'Una excepcional vil·la Belle Époque enfilada al Cap d\'Antibes amb vistes panoràmiques al mar des de cada habitació. La residència de 500 m² compta amb sis habitacions en suite, piscina infinita, celler de vi i jardí paisatgístic de més de 3.000 m².',
    },
    type: 'luxury',
    status: 'available',
    price: 8500000,
    priceLabel: '€8,500,000',
    bedrooms: 6,
    bathrooms: 6,
    receptionRooms: 3,
    squareMeters: 500,
    address: 'Chemin du Littoral 14',
    city: 'Antibes',
    postcode: '06160',
    country: 'France',
    coordinates: { lat: 43.5543, lng: 7.1313 },
    features: [
      { en: 'Infinity pool with sea views', fr: 'Piscine à débordement avec vue mer', es: 'Piscina infinita con vistas al mar', ca: 'Piscina infinita amb vistes al mar' },
      { en: 'Landscaped garden 3,000 m²', fr: 'Jardin paysager 3 000 m²', es: 'Jardín paisajístico 3.000 m²', ca: 'Jardí paisatgístic 3.000 m²' },
      { en: 'Wine cellar', fr: 'Cave à vin', es: 'Bodega', ca: 'Celler de vi' },
      { en: 'Home cinema', fr: 'Salle de cinéma', es: 'Cine en casa', ca: 'Cinema a casa' },
      { en: 'Triple garage', fr: 'Garage triple', es: 'Garaje triple', ca: 'Garatge triple' },
      { en: 'Smart home automation', fr: 'Domotique', es: 'Domótica', ca: 'Domòtica' },
    ],
    images: [IMG, IMG, IMG, IMG],
    agent: {
      id: 'agent-001',
      name: 'Sophie Marchand',
      slug: 'sophie-marchand',
      photo: IMG,
      title: { en: 'Senior Property Consultant', fr: 'Consultante Immobilière Senior', es: 'Consultora Inmobiliaria Senior', ca: 'Consultora Immobiliària Senior' },
      phone: '+33 6 12 34 56 78',
      email: 'sophie.marchand@sweetestate.eu',
    },
    listedAt: '2025-10-01',
  },

  // ── 3. Residential Rental — Paris ────────────────────────────────────────────
  {
    id: 'prop-003',
    slug: 'haussmann-apartment-paris-7eme',
    title: {
      en: 'Haussmann Apartment in the 7th Arrondissement',
      fr: 'Appartement Haussmannien dans le 7ème Arrondissement',
      es: 'Piso Haussmann en el 7° Distrito',
      ca: 'Pis Haussmann al 7è Districte',
    },
    description: {
      en: 'A beautifully appointed three-bedroom Haussmann-era apartment on the prestigious Rue du Bac. High ceilings, herringbone parquet floors, and original mouldings blend seamlessly with a contemporary renovation. Ideal for families or professionals seeking a prestigious Paris address.',
      fr: 'Un appartement haussmannien de trois chambres superbement aménagé dans la prestigieuse rue du Bac. Hauts plafonds, parquet en chevron et moulures d\'origine s\'allient harmonieusement à une rénovation contemporaine. Idéal pour les familles ou les professionnels en quête d\'une adresse parisienne prestigieuse.',
      es: 'Un piso de estilo haussmanniano con tres habitaciones exquisitamente equipado en la prestigiosa Rue du Bac. Techos altos, parquet en espiga y molduras originales se combinan a la perfección con una renovación contemporánea. Ideal para familias o profesionales que buscan una dirección parisina de prestigio.',
      ca: 'Un pis d\'estil haussmannià amb tres habitacions exquisidament equipat a la prestigiosa Rue du Bac. Sostres alts, parquet en espiga i motllures originals es combinen a la perfecció amb una renovació contemporània. Ideal per a famílies o professionals que busquen una adreça parisenca de prestigi.',
    },
    type: 'residential_rental',
    status: 'available',
    price: 4500,
    priceLabel: '€4,500 / month',
    bedrooms: 3,
    bathrooms: 2,
    receptionRooms: 1,
    squareMeters: 130,
    address: 'Rue du Bac 87, 3ème étage',
    city: 'Paris',
    postcode: '75007',
    country: 'France',
    coordinates: { lat: 48.8566, lng: 2.3277 },
    features: [
      { en: 'Herringbone parquet floors', fr: 'Parquet en chevron', es: 'Parquet en espiga', ca: 'Parquet en espiga' },
      { en: 'Original Haussmann mouldings', fr: 'Moulures haussmanniennes d\'origine', es: 'Molduras haussmannianas originales', ca: 'Motllures haussmanianes originals' },
      { en: 'Private courtyard garden', fr: 'Jardin de cour privé', es: 'Jardín de patio privado', ca: 'Jardí de pati privat' },
      { en: 'Concierge service', fr: 'Service de conciergerie', es: 'Servicio de conserjería', ca: 'Servei de consergeria' },
    ],
    images: [IMG, IMG, IMG],
    agent: {
      id: 'agent-003',
      name: 'Isabelle Dupont',
      slug: 'isabelle-dupont',
      photo: IMG,
      title: { en: 'Rental & Relocation Advisor', fr: 'Conseillère en Location & Relocalisation', es: 'Asesora de Alquiler y Reubicación', ca: 'Assessora de Lloguer i Trasllat' },
      phone: '+33 6 55 44 33 22',
      email: 'isabelle.dupont@sweetestate.eu',
    },
    listedAt: '2026-01-10',
  },

  // ── 4. Commercial — Madrid ───────────────────────────────────────────────────
  {
    id: 'prop-004',
    slug: 'boutique-office-madrid-salamanca',
    title: {
      en: 'Boutique Office Space in Salamanca',
      fr: 'Bureaux Boutique dans le Quartier Salamanca',
      es: 'Espacio de Oficinas Boutique en Salamanca',
      ca: 'Espai d\'Oficines Boutique al Barri de Salamanca',
    },
    description: {
      en: 'A fully fitted, plug-and-play office spanning 350 m² across two floors in Madrid\'s most sought-after business district. Features include a reception area, eight private offices, a boardroom, and a rooftop terrace. Available for long-term lease.',
      fr: 'Un bureau entièrement aménagé de 350 m² répartis sur deux niveaux dans le quartier d\'affaires le plus prisé de Madrid. Comprend une réception, huit bureaux privés, une salle de réunion et une terrasse sur le toit. Disponible en bail longue durée.',
      es: 'Una oficina totalmente equipada y lista para usar de 350 m² distribuidos en dos plantas en el distrito comercial más exclusivo de Madrid. Incluye recepción, ocho despachos privados, sala de juntas y terraza en la azotea. Disponible en arrendamiento a largo plazo.',
      ca: 'Una oficina totalment equipada i llesta per usar de 350 m² distribuïts en dues plantes al districte comercial més exclusiu de Madrid. Inclou recepció, vuit despatxos privats, sala de juntes i terrassa a la coberta. Disponible en arrendament a llarg termini.',
    },
    type: 'commercial',
    status: 'available',
    price: 9800,
    priceLabel: '€9,800 / month',
    bedrooms: 0,
    bathrooms: 2,
    receptionRooms: 1,
    squareMeters: 350,
    address: 'Calle de Serrano 45, 2ª planta',
    city: 'Madrid',
    postcode: '28001',
    country: 'Spain',
    coordinates: { lat: 40.4268, lng: -3.6885 },
    features: [
      { en: 'Rooftop terrace', fr: 'Terrasse sur le toit', es: 'Terraza en azotea', ca: 'Terrassa a la coberta' },
      { en: 'Fibre optic broadband', fr: 'Fibre optique haut débit', es: 'Banda ancha de fibra óptica', ca: 'Banda ampla de fibra òptica' },
      { en: 'Boardroom with AV system', fr: 'Salle de réunion avec système AV', es: 'Sala de juntas con sistema AV', ca: 'Sala de juntes amb sistema AV' },
      { en: 'Underground parking', fr: 'Parking souterrain', es: 'Aparcamiento subterráneo', ca: 'Aparcament subterrani' },
      { en: '24-hour security', fr: 'Sécurité 24h/24', es: 'Seguridad 24 horas', ca: 'Seguretat 24 hores' },
    ],
    images: [IMG, IMG],
    agent: {
      id: 'agent-002',
      name: 'Carlos Rivera',
      slug: 'carlos-rivera',
      photo: IMG,
      title: { en: 'Commercial & Investment Specialist', fr: 'Spécialiste Commercial & Investissement', es: 'Especialista en Comercial e Inversión', ca: 'Especialista en Comercial i Inversió' },
      phone: '+34 6 98 76 54 32',
      email: 'carlos.rivera@sweetestate.eu',
    },
    listedAt: '2025-12-05',
  },

  // ── 5. Residential Sale — Lisbon ─────────────────────────────────────────────
  {
    id: 'prop-005',
    slug: 'azulejo-townhouse-lisbon-alfama',
    title: {
      en: 'Azulejo Townhouse in Alfama',
      fr: 'Maison de Ville aux Azulejos à Alfama',
      es: 'Casa Adosada con Azulejos en Alfama',
      ca: 'Casa Adossada amb Azulejos a Alfama',
    },
    description: {
      en: 'A meticulously restored four-storey townhouse clad in traditional blue azulejo tiles, enjoying sweeping views over the River Tagus. The interior blends exposed stone walls with modern comforts: three bedrooms, a rooftop terrace, and a private garage.',
      fr: 'Une maison de ville de quatre étages méticuleusement restaurée, habillée de carreaux azulejos bleus traditionnels, offrant une vue imprenable sur le Tage. L\'intérieur marie murs en pierre apparente et conforts modernes : trois chambres, une terrasse sur le toit et un garage privé.',
      es: 'Una casa adosada de cuatro plantas meticulosamente restaurada, revestida con azulejos azules tradicionales, con amplias vistas sobre el río Tajo. El interior combina paredes de piedra vista con comodidades modernas: tres dormitorios, terraza en azotea y garaje privado.',
      ca: 'Una casa adossada de quatre plantes meticulosament restaurada, revestida amb rajoles d\'azulejo blau tradicionals, amb vistes panoràmiques al riu Tejo. L\'interior combina parets de pedra vista amb comoditats modernes: tres habitacions, terrassa a la coberta i garatge privat.',
    },
    type: 'residential_sale',
    status: 'under_offer',
    price: 780000,
    priceLabel: '€780,000',
    bedrooms: 3,
    bathrooms: 2,
    receptionRooms: 2,
    squareMeters: 175,
    address: 'Beco do Azinhal 8',
    city: 'Lisbon',
    postcode: '1100-069',
    country: 'Portugal',
    coordinates: { lat: 38.7139, lng: -9.1334 },
    features: [
      { en: 'Traditional azulejo tile facade', fr: 'Façade en carreaux azulejos traditionnels', es: 'Fachada de azulejos tradicionales', ca: 'Façana de rajoles d\'azulejo tradicionals' },
      { en: 'Rooftop terrace with Tagus views', fr: 'Terrasse sur le toit avec vue sur le Tage', es: 'Terraza en azotea con vistas al Tajo', ca: 'Terrassa a la coberta amb vistes al Tejo' },
      { en: 'Exposed stone walls', fr: 'Murs en pierre apparente', es: 'Paredes de piedra vista', ca: 'Parets de pedra vista' },
      { en: 'Private garage', fr: 'Garage privé', es: 'Garaje privado', ca: 'Garatge privat' },
    ],
    images: [IMG, IMG, IMG],
    agent: {
      id: 'agent-002',
      name: 'Carlos Rivera',
      slug: 'carlos-rivera',
      photo: IMG,
      title: { en: 'Commercial & Investment Specialist', fr: 'Spécialiste Commercial & Investissement', es: 'Especialista en Comercial e Inversión', ca: 'Especialista en Comercial i Inversió' },
      phone: '+34 6 98 76 54 32',
      email: 'carlos.rivera@sweetestate.eu',
    },
    listedAt: '2025-09-20',
  },

  // ── 6. Residential Rental — Lyon ─────────────────────────────────────────────
  {
    id: 'prop-006',
    slug: 'traboule-apartment-lyon-vieux-lyon',
    title: {
      en: 'Charming Apartment in Vieux-Lyon',
      fr: 'Appartement de Charme dans le Vieux-Lyon',
      es: 'Encantador Apartamento en el Vieux-Lyon',
      ca: 'Encantador Apartament al Vieux-Lyon',
    },
    description: {
      en: 'A light-filled two-bedroom apartment on the third floor of a Renaissance building in the UNESCO-listed Vieux-Lyon neighbourhood. Exposed stone vaulting, original terracotta tiles, and updated facilities make this an ideal base for professionals or couples.',
      fr: 'Un appartement lumineux de deux chambres au troisième étage d\'un immeuble Renaissance dans le quartier du Vieux-Lyon classé à l\'UNESCO. Voûtes en pierre apparente, tomettes d\'origine et équipements modernes en font une base idéale pour les professionnels ou les couples.',
      es: 'Un luminoso apartamento de dos habitaciones en el tercer piso de un edificio renacentista en el barrio del Vieux-Lyon, declarado Patrimonio de la Humanidad por la UNESCO. Bóvedas de piedra vista, baldosas de terracota originales e instalaciones actualizadas lo convierten en una base ideal para profesionales o parejas.',
      ca: 'Un lluminós apartament de dues habitacions al tercer pis d\'un edifici renaixentista al barri del Vieux-Lyon, declarat Patrimoni de la Humanitat per la UNESCO. Voltes de pedra vista, rajoles de terracota originals i instal·lacions actualitzades el converteixen en una base ideal per a professionals o parelles.',
    },
    type: 'residential_rental',
    status: 'available',
    price: 1800,
    priceLabel: '€1,800 / month',
    bedrooms: 2,
    bathrooms: 1,
    receptionRooms: 1,
    squareMeters: 75,
    address: 'Rue du Boeuf 22, 3ème étage',
    city: 'Lyon',
    postcode: '69005',
    country: 'France',
    coordinates: { lat: 45.7602, lng: 4.8267 },
    features: [
      { en: 'UNESCO heritage neighbourhood', fr: 'Quartier classé UNESCO', es: 'Barrio declarado por la UNESCO', ca: 'Barri declarat per la UNESCO' },
      { en: 'Exposed stone vaulting', fr: 'Voûtes en pierre apparente', es: 'Bóvedas de piedra vista', ca: 'Voltes de pedra vista' },
      { en: 'Original terracotta floor tiles', fr: 'Tomettes d\'origine', es: 'Baldosas de terracota originales', ca: 'Rajoles de terracota originals' },
      { en: 'Close to metro', fr: 'Proche du métro', es: 'Cerca del metro', ca: 'Prop del metro' },
    ],
    images: [IMG, IMG],
    agent: {
      id: 'agent-003',
      name: 'Isabelle Dupont',
      slug: 'isabelle-dupont',
      photo: IMG,
      title: { en: 'Rental & Relocation Advisor', fr: 'Conseillère en Location & Relocalisation', es: 'Asesora de Alquiler y Reubicación', ca: 'Assessora de Lloguer i Trasllat' },
      phone: '+33 6 55 44 33 22',
      email: 'isabelle.dupont@sweetestate.eu',
    },
    listedAt: '2026-02-01',
  },

  // ── 7. Commercial — Valencia ──────────────────────────────────────────────────
  {
    id: 'prop-007',
    slug: 'retail-unit-valencia-ciudad-artes',
    title: {
      en: 'Retail Unit near Ciudad de las Artes',
      fr: 'Local Commercial près de la Cité des Arts',
      es: 'Local Comercial cerca de la Ciudad de las Artes',
      ca: 'Local Comercial prop de la Ciutat de les Arts',
    },
    description: {
      en: 'A 220 m² retail unit with full glazed frontage on one of Valencia\'s busiest pedestrian thoroughfares, adjacent to the iconic Ciudad de las Artes y las Ciencias. Suitable for flagship retail, a restaurant, or a gallery. High foot traffic all year round.',
      fr: 'Un local commercial de 220 m² avec façade entièrement vitrée sur l\'une des artères piétonnes les plus fréquentées de Valence, adjacent à la Cité des Arts et des Sciences. Convient à une boutique phare, un restaurant ou une galerie. Fort passage piétonnier toute l\'année.',
      es: 'Un local comercial de 220 m² con fachada completamente acristalada en una de las arterias peatonales más concurridas de Valencia, adyacente a la icónica Ciudad de las Artes y las Ciencias. Apto para comercio insignia, restaurante o galería. Gran afluencia de peatones durante todo el año.',
      ca: 'Un local comercial de 220 m² amb façana totalment envidrada en una de les artèries peatonals més concorregudes de València, adjacent a l\'icònica Ciutat de les Arts i les Ciències. Apte per a comerç insígnia, restaurant o galeria. Gran afluència de vianants durant tot l\'any.',
    },
    type: 'commercial',
    status: 'available',
    price: 4200,
    priceLabel: '€4,200 / month',
    bedrooms: 0,
    bathrooms: 1,
    receptionRooms: 0,
    squareMeters: 220,
    address: 'Avinguda del Professor López Piñero 7',
    city: 'Valencia',
    postcode: '46013',
    country: 'Spain',
    coordinates: { lat: 39.4534, lng: -0.3566 },
    features: [
      { en: 'Full glazed frontage', fr: 'Façade entièrement vitrée', es: 'Fachada completamente acristalada', ca: 'Façana totalment envidrada' },
      { en: 'High foot traffic location', fr: 'Emplacement à fort passage piétonnier', es: 'Ubicación de alto tráfico peatonal', ca: 'Ubicació d\'alt trànsit peatonal' },
      { en: 'Loading bay access', fr: 'Accès quai de chargement', es: 'Acceso a muelle de carga', ca: 'Accés a moll de càrrega' },
      { en: 'Air conditioning', fr: 'Climatisation', es: 'Aire acondicionado', ca: 'Aire condicionat' },
    ],
    images: [IMG, IMG],
    agent: {
      id: 'agent-002',
      name: 'Carlos Rivera',
      slug: 'carlos-rivera',
      photo: IMG,
      title: { en: 'Commercial & Investment Specialist', fr: 'Spécialiste Commercial & Investissement', es: 'Especialista en Comercial e Inversión', ca: 'Especialista en Comercial i Inversió' },
      phone: '+34 6 98 76 54 32',
      email: 'carlos.rivera@sweetestate.eu',
    },
    listedAt: '2026-01-25',
  },

  // ── 8. Luxury — Mallorca ─────────────────────────────────────────────────────
  {
    id: 'prop-008',
    slug: 'finca-luxury-mallorca-deya',
    title: {
      en: 'Luxury Finca in Deià, Mallorca',
      fr: 'Finca de Luxe à Deià, Majorque',
      es: 'Finca de Lujo en Deià, Mallorca',
      ca: 'Finca de Luxe a Deià, Mallorca',
    },
    description: {
      en: 'A historic 17th-century finca lovingly restored to the highest standard, set on 5 hectares of terraced olive and almond groves above the artistic village of Deià. Five en-suite bedrooms, a heated pool, a bodega, and a separate guest cottage.',
      fr: 'Une finca historique du XVIIe siècle amoureusement restaurée selon les plus hauts critères, sur 5 hectares de terrasses d\'oliviers et d\'amandiers surplombant le village artistique de Deià. Cinq chambres en suite, piscine chauffée, bodega et dépendance indépendante pour les invités.',
      es: 'Una histórica finca del siglo XVII restaurada con esmero y según los más altos estándares, ubicada en 5 hectáreas de terrazas de olivos y almendros sobre el artístico pueblo de Deià. Cinco habitaciones en suite, piscina climatizada, bodega y una casa de invitados independiente.',
      ca: 'Una històrica finca del segle XVII restaurada amb molta cura i als més alts estàndards, ubicada en 5 hectàrees de terrasses d\'oliveres i ametllers sobre el poble artístic de Deià. Cinc habitacions en suite, piscina climatitzada, celler i una casa d\'hostes independent.',
    },
    type: 'luxury',
    status: 'available',
    price: 5900000,
    priceLabel: '€5,900,000',
    bedrooms: 5,
    bathrooms: 5,
    receptionRooms: 2,
    squareMeters: 420,
    address: 'Camí des Puig s/n',
    city: 'Deià',
    postcode: '07179',
    country: 'Spain',
    coordinates: { lat: 39.7485, lng: 2.6482 },
    features: [
      { en: '5 hectares of terraced olive groves', fr: '5 hectares de terrasses d\'oliviers', es: '5 hectáreas de terrazas de olivos', ca: '5 hectàrees de terrasses d\'oliveres' },
      { en: 'Heated pool', fr: 'Piscine chauffée', es: 'Piscina climatizada', ca: 'Piscina climatitzada' },
      { en: 'Traditional stone bodega', fr: 'Bodega traditionnelle en pierre', es: 'Bodega de piedra tradicional', ca: 'Celler de pedra tradicional' },
      { en: 'Independent guest cottage', fr: 'Dépendance indépendante', es: 'Casa de invitados independiente', ca: 'Casa d\'hostes independent' },
      { en: 'Mountain and sea views', fr: 'Vue montagne et mer', es: 'Vistas a la montaña y al mar', ca: 'Vistes a la muntanya i al mar' },
    ],
    images: [IMG, IMG, IMG, IMG],
    agent: {
      id: 'agent-001',
      name: 'Sophie Marchand',
      slug: 'sophie-marchand',
      photo: IMG,
      title: { en: 'Senior Property Consultant', fr: 'Consultante Immobilière Senior', es: 'Consultora Inmobiliaria Senior', ca: 'Consultora Immobiliària Senior' },
      phone: '+33 6 12 34 56 78',
      email: 'sophie.marchand@sweetestate.eu',
    },
    listedAt: '2025-08-15',
  },
]

// ─── Wire up agent.listings back-references ───────────────────────────────────

for (const agent of mockAgents) {
  agent.listings = mockProperties.filter((p) => p.agent.id === agent.id)
}
